### ISSUE TITLE
Support for restricting tests to just unit: or integration:

### ISSUE THREAD

**Issue by steffengates** [mjhugo/grails-auto-test#4]
We have a large app which takes quite a while to spin up for integration tests. During the unit testing phase, it would be great if I had to option to disable the integration tests and vice versa. I did this manually by editing the plugin's test script, but I feel like this should be a runtime option?

**Comment by mjhugo** [comment]
You can do this when you start AutoTest, see https://github.com/mjhugo/grails-auto-test/issues/1 for examples

**Comment by steffengates** [comment]
Can't believe I didn't see that, thank you for your time! I love the plugin!

--Steffen

**Comment by mjhugo** [comment]
No problem, I've added it to the README.md file so it'll be more apparent to the next person

**Comment by steffengates** [comment]
Thanks again - Hope the new year is treating you well.

Take it easy,
--Steffen
